### ISSUE TITLE
args: program does not follow specification

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#10]
Have a close look at #3 again. It shows sample output. Your program must produce the output just like that.

You may find it easier to use System.out.printf() instead of System.out.println() in this case. But it is your choice.

**Comment by mamashe** [comment]
when your run the Args.java and type in java Args abc def, it should print: 
abc
def

the only different is 
1. abc
2. def

and that is what i am trying to figure it out but can't number to sample output.

**Comment by lcabrini** [comment]
There is another difference as well: it should also print "Got 2 command-line arguments", before the list. You can get the number of command-line arguments with args.length.

To get a counter for the elements in the array, you have a few choices. Two of them are simpler, the others we shall discuss a bit later (the coolest one uses lambdas):

Create a variable outside of the for loop. In the loop increment it.

```
 int i = 1;
 for (String arg : args) {
     System.out.printf("%3d. %s\n", i, arg);
     ++i;
 }
```

You could shorten this a bit, but if you find the code to be less readable, avoid it.

```
int i = 0;
for (String arg : args) {
    System.out.printf("%3d. %s\n", ++i, arg);
}
```

Instead of the for each loop, use a tradional for loop. You will need to take into account that arrays in Java are 0 indexed but the printed list should start at 1 so you need to do i+1.

```
for (int i = 0; i < args.length; ++i) {
    System.out.printf("%3d. %s", i+1, args[i]);
}
```

Both of these are acceptable. You can choose the one that you like the best, but you should be aware of both, and know how to implement them.

**Comment by mamashe** [comment]
Though i have noted down the two codes but i prefer to go for number 1.

int i = 1
for (String arg : args) {
System.out.printf("%3d. %s\n", i, arg);
++i;
}

What i observe is code number 1. print out the arguments from 1 to the number of args it gets to but the second code: 
for (int i = 0; i < args.length; ++i) {
System.out.printf("%3d. %s", i, args[i]);
}
starts numbering from 0. yes i am aware arrays in java are 0 indexed, so I changed the code to for (int i = 1; i < args.length; ++i) and the result was "1. def instead of printing:
1. abc
2.def
it printed only 1. def. Moreover, The both codes did not print the "Got 2 command-line arguments".

Please explain to me what these two line codes do?

**Comment by lcabrini** [comment]
Since arrays are 0 indexed, the first element will be in args[0], the second in args[1], third in args[2] and so on. If the element has 5 elements then the last will be args[4] which could also be written as args[args.length - 1]. So to go through all the elements in the array, start at 0, continue until you are at args.length - 1. In other words.

```
for (int i = 0; i < args.length; ++i) {
```

But to print out the number in the output, we want to start at 1 then 2, 3, 4 ..., so in the output you have to do

```
i+1
```

**Comment by lcabrini** [comment]
The loop above will not print "Got 2 command-line arguments". It will only print out the elements. Am opening another ticket on that one.
