### ISSUE TITLE
Detail the name of the resulting class files in class name and file name experiment

### ISSUE THREAD

**Issue by lcabrini** [mamashe/sheila-java-learning#27]
Your summary of the relationship between class name and file name is good. However, I would like one other details. What is the name of the resulting .class files when you compile. Especially for point 3, is the resulting file called Different.class or Other.class?

**Comment by mamashe** [comment]
resulting.class files are all having the same class name with the exception of Different.java which has
    public class Other

when you compile, it does not give you the resulting.class file because of the public modifier. the resulting file name will be Different.class only if the class name is Different the same apply to the Other class vice versa.
